import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { sanityClient, urlFor } from "../lib/sanity";
import Link from "next/link";

const recipeQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage{
    asset->{
      _id, url
    }
  }
}`;
export default function Home({ recipes }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kitchen </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to My Kitchen</h1>

      <ul className="recipes-list">
        {recipes?.length > 0 &&
          recipes.map((recipe) => (
            <li key={recipe._id} className="recipe-card">
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <img src={urlFor(recipe.mainImage).url()} />
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
      </ul>
    </div>
  );
}

export async function getStaticProps() {
  const recipes = await sanityClient.fetch(recipeQuery);

  return {
    props: {
      recipes,
    },
  };
}
